version: "3.7"
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"

  gateway:
    build:
      context: ./backend_gateway
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8081:8081"

  session:
    build:
      context: ./backend_session
      dockerfile: Dockerfile
    restart: always
    networks:
      - common
      - session
    ports:
      - "8082:8082"

  publication:
    build:
      context: ./backend_publication
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - session
    networks:
      - common
      - publication
    ports:
      - "8083:8083"

  subscription:
    build:
      context: ./backend_subscription
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - session
      - publication
    networks:
      - common
      - subscription
    ports:
      - "8084:8084"

  statistics:
    build:
      context: ./backend_statistics
      dockerfile: Dockerfile
    networks:
      - common
      - statistics
    restart: always
    ports:
      - "8085:8085"

networks:
  common:
    driver: bridge
  session:
    driver: bridge
  publication:
    driver: bridge
  subscription:
    driver: bridge
  statistics:
    driver: bridge
