# Generated by Django 4.0.6 on 2022-08-17 16:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('publication_uid', models.UUIDField()),
                ('viewer_uid', models.UUIDField(blank=True, null=True)),
                ('view_date', models.DateTimeField(auto_now_add=True, verbose_name='date viewed')),
            ],
        ),
    ]
