# Generated by Django 4.0.6 on 2022-08-01 17:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_uid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('type', models.CharField(choices=[('user', 'user'), ('tag', 'tag')], max_length=4)),
                ('follower_uid', models.UUIDField(editable=False)),
                ('following_uid', models.UUIDField(editable=False)),
                ('sub_date', models.DateTimeField(auto_now_add=True, verbose_name='date subscribed')),
            ],
        ),
    ]
